AllCops:
  DisplayCopNames: true
  Include:
    - '**/*.thor'
    - '**/*.rake'
  Exclude:
    - 'bin/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'

Metrics/LineLength:
  AllowURI: true
    - http
    - https
  Max: 128

Style/Documentation:
  Enabled: false
