#!/bin/sh
# build assets for deployment
set -e

yarn install

yarn build:js:production
$(yarn bin)/uglifyjs public/bundle.js > public/bundle.min.js

yarn build:css
$(yarn bin)/csswring public/bundle.css > public/bundle.min.css

rm -rf public/bundle.js public/bundle.css
rm -rf node_modules
